version: '3.8'

services:
  shoporiadb:
    container_name: shoporiadb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Yaser@2003
      - POSTGRES_DB=ShoporiaDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_shoporiadb:/var/lib/postgresql/data/

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "5341:5341"
      - "9091:80"